name: Android CI

on:
  push:
    branches: [ main, "feature/**" ]
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - uses: android-actions/setup-android@v3

      - name: Install SDK packages
        run: sdkmanager "platforms;android-34" "build-tools;35.0.0"

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest --no-daemon
